spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://39.104.166.109:3306/iot_dev?characterEncoding=utf8&useSSL=false
    username: iottest
    password: Links@2018$
server:
  port: 15023
---
spring:
  profiles: uat
  datasource:
    url: jdbc:mysql://39.104.166.109:3306/iot_dev?characterEncoding=utf8&useSSL=false
    username: iottest
    password: Links@2018$
server:
  port: 15022
---
logging:
  config: classpath:conf/logback-dev.xml
  level:
    com:
      cdtelecom:
        mapper: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
#    password: redis20190618
    timeout: 10
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
#redisExpireTime: 120
mybatis:
  type-aliases-package: com.cdtelecom.po


bizMap: '{
 A01:''openDataFlowLogic''
,A02:''test2''
,A03:''test2''
,A07:''test2''
,A09:''test2''
}'


testP: test22222

cd:
  ip: 47.244.97.56